version: '3.7'

services:

  goapp:
    build:
      context: ./
      dockerfile: docker/golang/Dockerfile
    command: go run cmd/ova-template-api/main.go
    ports:
      - "127.0.0.1:3009:82"
    volumes:
      - ./:/app

  golint:
    build:
      context: ./docker/golang-lint
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  goproto:
    build:
      context: ./
      dockerfile: docker/golang-protoc/Dockerfile
    volumes:
      - ./:/app

  gomock:
    build:
      context: ./
      dockerfile: docker/golang-mockgen/Dockerfile
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "127.0.0.1:5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
