// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: api/hero.proto

package ova_game_api

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeHero int32

const (
	TypeHero_Magician TypeHero = 0
	TypeHero_Fighter  TypeHero = 1
	TypeHero_Shooter  TypeHero = 2
)

// Enum value maps for TypeHero.
var (
	TypeHero_name = map[int32]string{
		0: "Magician",
		1: "Fighter",
		2: "Shooter",
	}
	TypeHero_value = map[string]int32{
		"Magician": 0,
		"Fighter":  1,
		"Shooter":  2,
	}
)

func (x TypeHero) Enum() *TypeHero {
	p := new(TypeHero)
	*p = x
	return p
}

func (x TypeHero) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeHero) Descriptor() protoreflect.EnumDescriptor {
	return file_api_hero_proto_enumTypes[0].Descriptor()
}

func (TypeHero) Type() protoreflect.EnumType {
	return &file_api_hero_proto_enumTypes[0]
}

func (x TypeHero) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeHero.Descriptor instead.
func (TypeHero) EnumDescriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{0}
}

type CreateHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Hero `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *CreateHeroRequest) Reset() {
	*x = CreateHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHeroRequest) ProtoMessage() {}

func (x *CreateHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHeroRequest.ProtoReflect.Descriptor instead.
func (*CreateHeroRequest) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHeroRequest) GetTask() *Hero {
	if x != nil {
		return x.Task
	}
	return nil
}

type DescribeHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DescribeHeroRequest) Reset() {
	*x = DescribeHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeHeroRequest) ProtoMessage() {}

func (x *DescribeHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeHeroRequest.ProtoReflect.Descriptor instead.
func (*DescribeHeroRequest) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeHeroRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveHeroRequest) Reset() {
	*x = RemoveHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHeroRequest) ProtoMessage() {}

func (x *RemoveHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHeroRequest.ProtoReflect.Descriptor instead.
func (*RemoveHeroRequest) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveHeroRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListHeroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListHeroRequest) Reset() {
	*x = ListHeroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroRequest) ProtoMessage() {}

func (x *ListHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroRequest.ProtoReflect.Descriptor instead.
func (*ListHeroRequest) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{3}
}

func (x *ListHeroRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListHeroRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListHeroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heroes []*Hero `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
}

func (x *ListHeroResponse) Reset() {
	*x = ListHeroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHeroResponse) ProtoMessage() {}

func (x *ListHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHeroResponse.ProtoReflect.Descriptor instead.
func (*ListHeroResponse) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{4}
}

func (x *ListHeroResponse) GetHeroes() []*Hero {
	if x != nil {
		return x.Heroes
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hero *Hero `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGameResponse) GetHero() *Hero {
	if x != nil {
		return x.Hero
	}
	return nil
}

type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId string   `protobuf:"bytes,1,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	UserId uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type   TypeHero `protobuf:"varint,4,opt,name=type,proto3,enum=ova.game.api.TypeHero" json:"type,omitempty"`
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hero_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_api_hero_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_api_hero_proto_rawDescGZIP(), []int{6}
}

func (x *Hero) GetHeroId() string {
	if x != nil {
		return x.HeroId
	}
	return ""
}

func (x *Hero) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Hero) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hero) GetType() TypeHero {
	if x != nil {
		return x.Type
	}
	return TypeHero_Magician
}

var File_api_hero_proto protoreflect.FileDescriptor

var file_api_hero_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x6f, 0x76, 0x61, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65,
	0x72, 0x6f, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x23, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x72, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3e, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x72,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x72,
	0x6f, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x76, 0x61, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x06, 0x68,
	0x65, 0x72, 0x6f, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x68,
	0x65, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x76, 0x61, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x04, 0x68,
	0x65, 0x72, 0x6f, 0x22, 0x77, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x48,
	0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48, 0x65, 0x72,
	0x6f, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x32, 0x0a, 0x08,
	0x54, 0x79, 0x70, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x61, 0x67, 0x69,
	0x63, 0x69, 0x61, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x69, 0x67, 0x68, 0x74, 0x65,
	0x72, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x10, 0x02,
	0x32, 0xb9, 0x02, 0x0a, 0x07, 0x48, 0x65, 0x72, 0x6f, 0x41, 0x70, 0x69, 0x12, 0x4f, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x1f, 0x2e, 0x6f, 0x76, 0x61,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6f, 0x76,
	0x61, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6f, 0x76,
	0x61, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48,
	0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x76, 0x61,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x65,
	0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x21, 0x2e, 0x6f, 0x76, 0x61,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48,
	0x65, 0x72, 0x6f, 0x12, 0x1f, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x3e, 0x5a, 0x3c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x76,
	0x61, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x3b,
	0x6f, 0x76, 0x61, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_hero_proto_rawDescOnce sync.Once
	file_api_hero_proto_rawDescData = file_api_hero_proto_rawDesc
)

func file_api_hero_proto_rawDescGZIP() []byte {
	file_api_hero_proto_rawDescOnce.Do(func() {
		file_api_hero_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_hero_proto_rawDescData)
	})
	return file_api_hero_proto_rawDescData
}

var file_api_hero_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_hero_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_hero_proto_goTypes = []interface{}{
	(TypeHero)(0),               // 0: ova.game.api.TypeHero
	(*CreateHeroRequest)(nil),   // 1: ova.game.api.CreateHeroRequest
	(*DescribeHeroRequest)(nil), // 2: ova.game.api.DescribeHeroRequest
	(*RemoveHeroRequest)(nil),   // 3: ova.game.api.RemoveHeroRequest
	(*ListHeroRequest)(nil),     // 4: ova.game.api.ListHeroRequest
	(*ListHeroResponse)(nil),    // 5: ova.game.api.ListHeroResponse
	(*CreateGameResponse)(nil),  // 6: ova.game.api.CreateGameResponse
	(*Hero)(nil),                // 7: ova.game.api.Hero
	(*empty.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_api_hero_proto_depIdxs = []int32{
	7, // 0: ova.game.api.CreateHeroRequest.task:type_name -> ova.game.api.Hero
	7, // 1: ova.game.api.ListHeroResponse.heroes:type_name -> ova.game.api.Hero
	7, // 2: ova.game.api.CreateGameResponse.hero:type_name -> ova.game.api.Hero
	0, // 3: ova.game.api.Hero.type:type_name -> ova.game.api.TypeHero
	1, // 4: ova.game.api.HeroApi.CreateHero:input_type -> ova.game.api.CreateHeroRequest
	4, // 5: ova.game.api.HeroApi.ListHeroes:input_type -> ova.game.api.ListHeroRequest
	2, // 6: ova.game.api.HeroApi.DescribeHero:input_type -> ova.game.api.DescribeHeroRequest
	3, // 7: ova.game.api.HeroApi.RemoveHero:input_type -> ova.game.api.RemoveHeroRequest
	6, // 8: ova.game.api.HeroApi.CreateHero:output_type -> ova.game.api.CreateGameResponse
	5, // 9: ova.game.api.HeroApi.ListHeroes:output_type -> ova.game.api.ListHeroResponse
	8, // 10: ova.game.api.HeroApi.DescribeHero:output_type -> google.protobuf.Empty
	8, // 11: ova.game.api.HeroApi.RemoveHero:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_hero_proto_init() }
func file_api_hero_proto_init() {
	if File_api_hero_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_hero_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hero_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hero_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hero_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHeroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hero_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHeroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hero_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hero_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_hero_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hero_proto_goTypes,
		DependencyIndexes: file_api_hero_proto_depIdxs,
		EnumInfos:         file_api_hero_proto_enumTypes,
		MessageInfos:      file_api_hero_proto_msgTypes,
	}.Build()
	File_api_hero_proto = out.File
	file_api_hero_proto_rawDesc = nil
	file_api_hero_proto_goTypes = nil
	file_api_hero_proto_depIdxs = nil
}
